create table if not exists livros (
    id serial primary key,
    titulo text not null,
    autor text not null,
    descricao text not null
);

insert into livros (titulo, autor, descricao) values 
('O Hobbit', 'J.R.R. Tolkien', 'Lançado em 1937, O Hobbit é um divisor de águas na literatura fantástica mundial. Mais de 80 anos após a sua publicação, o livro que antecede os ocorridos em O Senhor dos Anéis continua arrebatando fãs de todas as idades, talvez pelo seu tom brincalhão com uma pitada de magia élfica, ou talvez porque J.R.R. Tolkien tenha escrito o melhor livro infanto-juvenil de todos os tempos.'),
('1984', 'George Orwell', 'Publicada originalmente em 1949, a distopia futurista 1984 é um dos romances mais influentes do século XX, um inquestionável clássico moderno. Lançada poucos meses antes da morte do autor, é uma obra magistral que ainda se impõe como uma poderosa reflexão ficcional sobre a essência nefasta de qualquer forma de poder totalitário.'),
('Admirável mundo novo', 'Aldous Leonard Huxley', 'Um clássico moderno, o romance distópico de Aldous Huxley é incontornável para quem procura um dos exemplos mais marcantes da tematização de estados autoritários, ao lado de 1984, de George Orwell.'),
('A bússola de ouro', 'Philip Pullman', 'Lyra Belacqua e seu daemon, Pantalaimon, vivem felizes e soltos entre os catedráticos da Faculdade Jordan, em Oxford. Até que rumores invadem a cidade – são boatos sobre os Papões, sequestradores de crianças que estão espalhando o medo pelo país.'),
('As Brumas de Avalon (Ciclo de Avalon Livro 1)', 'Marion Zimmer Bradley', 'Por séculos, as lendas arturianas povoaram o imaginário de leitores de todo o mundo. As brumas de Avalon é considerado por muitos a versão literária definitiva do mito e muitas gerações de mulheres se deixaram arrebatar pela escrita envolvente de Marion Zimmer Bradley.'),
('Uma dobra no tempo', 'Madeleine Engle', 'Um clássico da fantasia e da ficção científica emerge!Após uma noite de forte tempestade, uma visita estranha chega à casa da família Murry e convoca Meg, seu irmão Charles Wallace e o amigo deles, Calvin OKeefe para uma aventura muito perigosa e extraordinária – uma viagem que ameaçará suas vidas e o nosso universo.'),
('Jogos vorazes', 'Suzane Collins', 'Na abertura dos Jogos Vorazes, a organização não recolhe os corpos dos combatentes caídos e dá tiros de canhão até o final. Cada tiro, um morto. Onze tiros no primeiro dia. Treze jovens restaram, entre eles, Katniss. Para quem os tiros de canhão serão no dia seguinte?'),
('A rainha vermelha', 'Victoria Aveyard', 'O mundo de Mare Barrow é dividido pelo sangue: vermelho ou prateado. Mare e sua família são vermelhos: plebeus, humildes, destinados a servir uma elite prateada cujos poderes sobrenaturais os tornam quase deuses. Mare rouba o que pode para ajudar sua família a sobreviver e não tem esperanças de escapar do vilarejo miserável onde mora. Entretanto, numa reviravolta do destino, ela consegue um emprego no palácio real, onde, em frente ao rei e a toda a nobreza, descobre que tem um poder misterioso…'),
('Harry Potter', 'J.K. Rowling', 'Uma nova edição impressionante de Harry Potter e a Pedra Filosofal! Experimente a história de magia mais amada do mundo de uma nova forma. Totalmente ilustrada em cores brilhantes, com capa dura e elementos interativos artesanais em papel, criados pelo premiado estúdio MinaLima, essa nova versão do primeiro livro da série Harry Potter vai encantar os leitores de todas as idades!'),
('Duna', 'Frank Herbert', 'Duna é um triunfo da imaginação, que influenciará a literatura para sempre.Esta edição inédita, com introdução de Neil Gaiman, apresenta ao leitor o universo fantástico criado por Herbert e que será adaptado ao cinema por Denis Villeneuve, diretor de A chegada e de Blade Runner 2049.'),
('Fahrenheit 451', 'Ray Bradbury', 'Guy Montag é um bombeiro. Sua profissão é atear fogo nos livros. Em um mundo onde as pessoas vivem em função das telas e a literatura está ameaçada de extinção, os livros são objetos proibidos, e seus portadores são considerados criminosos.'),
('O nome do vento: A crônica do matador do Rei', 'Patrick Rothfuss', 'Ninguém sabe ao certo quem é o herói ou o vilão desse fascinante universo criado por Patrick Rothfuss. Na realidade, essas duas figuras se concentram em Kote, um homem enigmático que se esconde sob a identidade de proprietário da hospedaria Marco do Percurso.'),
('Alice no país das maravilhas', 'Lewis Carrol', 'Uma menina, um coelho e uma história capazes de fazer qualquer um de nós voltar a sonhar. Alice é despertada de um leve sono ao pé de uma árvore por um coelho peculiar. Uma criatura alva e falante com roupas engraçadas, que consulta seu relógio e reclama do próprio atraso.'),
('As crônicas de Nárnia', 'C. S. Lewis', 'Viagens ao fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal - o que mais um leitor poderia querer de um livro?'),
('Ciclo da herança', 'Christopher Paolini', 'Coleção Aventuras Encantadas O vento uiva pela noite trazendo consigo um aroma capaz de mudar o mundo. Quando Eragon encontra na floresta uma pedra azul polida, acredita que poderá ser uma descoberta de sorte para um simples rapaz do campo: talvez sirva para comprar carne que alimentará a família durante o inverno. Mas, no momento em que um dragão nasce de dentro da pedra, Eragon percebe que está diante de um legado quase tão antigo quanto o do próprio Império.'),
('O gigante enterrado', 'Kazuo Ishiguro', 'Uma terra marcada por guerras recentes e amaldiçoada por uma misteriosa névoa do esquecimento. Uma população desnorteada diante de ameaças múltiplas. Um casal que parte numa jornada em busca do filho e no caminho terá seu amor posto à prova - será nosso sentimento forte o bastante quando já não há reminiscências da história que nos une?'),
('O aprendiz de assassino', 'Robin Hobb', 'Fitz tem seis anos de idade quando seu avô o joga aos pés de um guarda real e anuncia que a partir de então o pai deve cuidar do bastardo que produziu ― e o pai de Fitz é ninguém menos que Chilvary Farseer, o príncipe herdeiro dos Seis Ducados.'),
('O Olho do Mundo', 'Robert Jordan', 'Um dia houve uma guerra tão definitiva que rompeu o mundo, e no girar da Roda do Tempo o que ficou na memória dos homens virou esteio das lendas. Como a que diz que, quando as forças tenebrosas se reerguerem, o poder de combatê-las renascerá em um único homem, o Dragão, que trará de volta a guerra, e, de novo, tudo se fragmentará.'),
('As Mentiras de Locke Lamora', 'Scott Lynch', 'O Espinho é uma figura lendária: um espadachim imbatível, um especialista em roubos vultosos, um fantasma que atravessa paredes. Metade da excêntrica cidade de Camorr acredita que ele seja um defensor dos pobres, enquanto o restante o considera apenas uma invencionice ridícula.'),
('Limites da Fundação', 'Isaac Asimov', 'A humanidade está em risco. Uma ciência revolucionária prevê uma longa e inevitável era de trevas e barbárie. Para evitar que isso aconteça, o chamado plano Seldon é colocado em prática ao longo de séculos, e percorre a história da galáxia, prevendo conflitos de nossa civilização. Mas poderá o comportamento humano obedecer a um padrão científico?');